### ISSUE TITLE
Populate grids with document returned from OTS without needing full page refresh

### ISSUE THREAD

**Issue by axfelix** [kaschioudi/ojs3-markup#14]
UX testing with @jmacgreg confirmed that this is worth fixing -- we need to get a better understanding of OJS3's js implementation so that full page refreshes aren't required to see new documents returned from the stack. This can also affect launching Texture without a full refresh.

**Comment by kaschioudi** [comment]
Once the job is completed, the grid will reload after 5 seconds pause. Note that we need to wait few seconds to let backend download job archive and extract the xml document. But this is transparent to the user because the job status is only updated after the pause.
@axfelix : is that good enough or we should refresh the grid on modal close? (I believe refreshing the grid on modal close will be trickier to implemented)

**Comment by axfelix** [comment]
This is fine -- I didn't realize that the grid would reload after 5 seconds. Is the 5 second timeout currently specified manually, i.e., could we make it 1-2 seconds? That's just as effective as implementing the on-close behaviour, I think, if it's less difficult to implement.
