### ISSUE TITLE
Moving XML from "Production Ready Files" to "Galleys"

### ISSUE THREAD

**Issue by Vitaliy-1** [kaschioudi/ojs3-markup#19]
Greetings,

I have tested the plugin, and definitely can say, that there is a need to add option for moving edited JATS XML from Production Ready filles to Galleys. 
If we edit XML in all stages, it is necessary to use this edited file as galley.

Thanks for really great work!

**Comment by axfelix** [comment]
Hi Vitaliy,

Thanks for your feedback! Currently, it should be possible to move XML from a prior stage of the workflow to the Production Ready stage, and then, when you generate galleys from the Production Ready XML using the plugin, the XML should be one of the galleys "generated" (along with, optionally, ePub and PDF). It might be a bit unintuitive currently since that XML file isn't actually being changed at all -- it's being passed directly back from the stack after being used as input to create the other galleys.

We'll look into improving this from a UX perspective, just want to confirm that the feature is currently working.

**Comment by pilasou** [comment]
I think I have had the same problem. The use case is as followed: the author make a submission in Word, all reviews are made using this format. At the Copyediting stage, the XML file is generated and all editing is made directly in the XML using Texture. The XML file is the only production ready file and is "Sent to production". The option to produce the Galley files before Publication is not available with this format (see image
![galley_files](https://cloud.githubusercontent.com/assets/19291880/23767989/843f58b4-04d8-11e7-9221-641c32bc7c9b.PNG)
)

**Comment by axfelix** [comment]
Oh, sorry! This was actually the very last bug we flagged internally before the test went out, and I may have cloned the wrong build down for the test installs I sent. The "generate galleys" action wasn't appearing on XML files, only Word/PDF at that stage, which _does_ break the ability to carry forward changes to publication. I'll see if I can update the test instances now.

**Comment by axfelix** [comment]
This should be fixed in the current plugin code.
